version: '3.3'
x-uffizzi:
  ingress:
    service: app
    port: 80

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "80:80"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
volumes:
  data:
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: alist
    image: 'xhofe/alist:latest'
