x-uffizzi:
  ingress:
    service: alist
    port: 8080
services:
  alist:
    restart: always
    volumes:
      - share_data:/opt/alist/data
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: alist
    image: xhofe/alist:latest
volumes:
 share_data:
