x-uffizzi:
  ingress:
    service: alist
    port: 80
services:
    memory: 4000M
    restart: always
    volumes:
      - share_data:/opt/alist/data
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    privileged: true
    container_name: alist
    image: xhofe/alist:latest
volumes:
 share_data:
